services:
  xmpp-server:
    image: prosodyim/prosody:13.0
    container_name: mas_xmpp_server
    ports:
      - "5222:5222"
      - "5280:5280"
    volumes:
      - ./prosody.cfg.lua:/etc/prosody/prosody.cfg.lua
    user: root
